apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: iperf3
  name: iperf3
  namespace: nos-automation
spec:
  replicas: 2
  selector:
    app: iperf3
    deploymentconfig: iperf3
  template:
    metadata:
      labels:
        app: iperf3
        deploymentconfig: iperf3
    spec:
      containers:
      - image: quay.io/wguo/iperf3-tool:latest
        imagePullPolicy: Always
        name: iperf3
        ports:
        - containerPort: 5201
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
