apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-07-18T08:12:21Z
  labels:
    app: iperf3
  name: iperf3
  namespace: nos-automation
spec:
  ports:
  - port: 5201
    protocol: TCP
    targetPort: 5201
  selector:
    deploymentconfig: iperf3
  sessionAffinity: None
  type: ClusterIP
